language: python
sudo: false
python:
  - "3.4"
install:
  - npm install -g less coffee-script
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
script:
  - python manage.py flake8
  - coverage run manage.py test
after_success:
  - coveralls
