language: python
sudo: false
python:
  - "3.4"
install:
  - npm install -g less coffee-script
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install flake8
script:
  - flake8 --config .flake8 _1327
  - coverage run manage.py test
after_success:
  - coveralls
