language: python
python:
  - "3.4"
install:
  - npm install -g less
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - coverage run manage.py test _1327.main
  - coverage run manage.py test _1327.information_pages
after_success:
  - coveralls
