language: python
python:
  - "3.4"
install:
  - npm install -g less coffee-script
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - coverage run manage.py test
after_success:
  - coveralls
